server:
  port: 8081

topic:
  name: t.food.order

spring:
  data:
    mongodb:
      uri: mongodb://root:Rm3MpB4vR5AXPL@172.22.4.160:6400/MDMQ_NOTIFICACIONES_CORREO?authSource=admin
  kafka:
    consumer:
      auto-offset-reset: earliest
      session-timeout-ms: 125000
variables:
    propiedades:
        #tiempo en minutos
        tiempoEsperaServidor: 1
        cantidadCorreosEnviados: 2
servidor:
  url_kafka: 172.22.4.106:9092